export function buildProfileRoute({
  account,
  app,
  auth,
  clients,
  editor,
  media,
  profile,
  route,
  settings,
  settingsState,
  showToast,
  workspace
}) {
  return {
    setAccountDeleteOpen: account.setAccountDeleteOpen,
    setAccountDeleteText: account.setAccountDeleteText,
    setActiveTab: route.setActiveTab,
    openEditorRoom: editor.runtime.openRoom,
    props: {
      activeProfileSection: profile.activeProfileSection,
      activeProfileSectionMeta: profile.activeProfileSectionMeta,
      authBusy: auth.authBusy,
      canManageWorkspace: workspace.canManageWorkspace,
      copyToClipboard: app.copyToClipboard,
      handleClearCsvMigrationData: clients.actions.handleClearCsvMigrationData,
      handleCsvMigrationImport: clients.actions.handleCsvMigrationImport,
      handlePersonalProfilePhotoUpload: media.handlePersonalProfilePhotoUpload,
      handleProfileActivityOpen: profile.handleProfileActivityOpen,
      handleSettingChange: settingsState.handleSettingChange,
      handleSettingImageUpload: media.handleSettingImageUpload,
      handleSignOut: auth.handleSignOut,
      handleVenuePhotoUpload: media.handleVenuePhotoUpload,
      importedMigrationCounts: clients.importedMigrationCounts,
      isGuestWorkspace: workspace.isGuestWorkspace,
      keepLoggedIn: auth.keepLoggedIn,
      openBillingAction: account.openBillingAction,
      openOwnerAuth: auth.openOwnerAuth,
      openSettingImageCrop: media.openSettingImageCrop,
      personalDisplayName: workspace.personalDisplayName,
      personalProfile: workspace.personalProfile,
      profileActivityPrimaryCount: profile.profileActivityPrimaryCount,
      profileActivityRows: profile.profileActivityRows,
      profileActivitySecondaryCount: profile.profileActivitySecondaryCount,
      profileSections: profile.profileSections,
      profileSystemFilter: profile.profileSystemFilter,
      profileSystemFilterOptions: profile.profileSystemFilterOptions,
      referralUrl: workspace.referralUrl,
      removeFaqItem: settingsState.removeFaqItem,
      removePersonalProfilePhoto: media.removePersonalProfilePhoto,
      removeSettingImage: media.removeSettingImage,
      removeVenuePhoto: media.removeVenuePhoto,
      saveProfileChanges: settingsState.saveProfileChanges,
      setActiveProfileSection: profile.setActiveProfileSection,
      setKeepLoggedIn: auth.setKeepLoggedIn,
      setProfileSystemFilter: profile.setProfileSystemFilter,
      setShowOwnerManual: profile.setShowOwnerManual,
      settings,
      showToast,
      toggleFaqFeature: settingsState.toggleFaqFeature,
      updateFaqItem: settingsState.updateFaqItem,
      addFaqItem: settingsState.addFaqItem,
      updatePersonalProfile: settingsState.updatePersonalProfile,
      user: auth.user,
      venuePhotos: profile.venuePhotos,
      workspaceOwnerId: workspace.workspaceOwnerId,
      workspaceRole: workspace.workspaceRole
    }
  };
}
