export const readableAuthError = (error, fallback = 'Could not sign in.') => {
  const code = error?.code || '';
  if (code === 'auth/invalid-credential' || code === 'auth/user-not-found' || code === 'auth/wrong-password') return 'Email or password does not match an account yet.';
  if (code === 'auth/invalid-email') return 'Enter a valid email address.';
  if (code === 'auth/missing-password') return 'Enter your password to continue.';
  if (code === 'auth/email-already-in-use') return 'That email already has an account. Switch to Sign In instead.';
  if (code === 'auth/weak-password') return 'Use a password with at least 6 characters.';
  if (code === 'auth/too-many-requests') return 'Too many attempts. Wait a moment, then try again.';
  if (code === 'auth/network-request-failed') return 'Network connection dropped before sign-in finished.';
  if (code === 'auth/operation-not-allowed') return 'This sign-in method is not enabled in Firebase Authentication yet.';
  if (code === 'auth/admin-restricted-operation') return 'This sign-in method is restricted in Firebase Authentication.';
  if (code === 'auth/unauthorized-domain') return 'This domain is not allowed for Firebase sign-in yet.';
  if (code === 'auth/popup-closed-by-user') return 'Google sign-in was closed before it finished.';
  if (code === 'auth/popup-blocked') return 'The browser blocked the Google sign-in popup. Try again or allow popups for this site.';
  if (code === 'auth/cancelled-popup-request') return 'Another Google sign-in window is already open. Finish that one or try again.';
  if (code === 'auth/web-storage-unsupported') return 'This browser is blocking secure sign-in storage. Enable storage/cookies or try another browser.';
  if (code === 'auth/invalid-api-key') return 'This build has an invalid Firebase API key. Check the Firebase config and redeploy.';
  if (code === 'auth/internal-error') return 'Secure sign-in hit a temporary Firebase issue. Refresh and try again.';
  return fallback;
};
