import { createDefaultCommunications } from './communicationsConfig';

export const createDefaultSettings = () => ({
  slug: 'your-business',
  brandName: 'Your Business',
  welcomeMessage: 'Reserve your session.',
  tagline: 'Online bookings',
  primaryColor: '#050505',
  headingColor: '#000000',
  bodyColor: '#666666',
  backgroundColor: '#ffffff',
  slotBgColor: '#F8FAFC',
  slotTextColor: '#000000',
  dateBgColor: 'transparent',
  dateTextColor: '#666666',
  dateActiveBgColor: '#050505',
  dateActiveTextColor: '#ffffff',
  buttonTextColor: '#ffffff',
  fontFamily: 'inter',
  nativeAccent: true,
  editorPaletteFlowColor: 'blue',
  editorColorDepth: 50,
  editorColorDepths: {},
  editorColorMix: ['blue'],
  headingFontFamily: '',
  bodyFontFamily: '',
  buttonFontFamily: '',
  slotFontFamily: '',
  dateFontFamily: '',
  brandNameSize: 76,
  brandNameFontFamily: '',
  taglineSize: 9,
  taglineFontFamily: '',
  welcomeSize: 20,
  welcomeFontFamily: '',
  interfaceStyleDirection: 'native-precision',
  buttonStyle: 'pill',
  availabilityStyle: 'solid',
  dateStyle: 'solid',
  timeSlotStyle: 'solid',
  actionButtonStyle: 'solid',
  calendarDisplayStyle: 'studio',
  timeDisplayStyle: 'pill',
  serviceDisplayStyle: 'signature',
  serviceDropdownEnabled: false,
  serviceBorderStyle: 'solid',
  faqStyle: 'minimal',
  faqDisplayStyle: 'accordion',
  faqBgColor: 'transparent',
  faqBorderColor: '#00000020',
  faqTextColor: '',
  faqAnswerColor: '',
  faqFontFamily: '',
  venueGalleryStyle: 'mosaic',
  venueTitle: 'Inside the space',
  venueIntro: 'See the place before you book.',
  mapDisplayStyle: 'card',
  socialIconStyle: 'outline',
  socialDisplayStyle: 'icons',
  socialIconBgColor: 'transparent',
  socialIconColor: '',
  socialIconTextColor: '',
  dateLabel: 'Which day are you looking to book ?',
  timeLabel: 'Lets see what time works',
  buttonText: 'Book Now',
  confirmButtonText: 'Confirm Booking',
  detailsHeading: 'Your Details',
  detailsSubHeading: 'Secure Your Slot',
  successHeading: 'Booking Confirmed!',
  availableTimes: ['09:00', '10:30', '12:00', '14:30', '16:00', '17:30'],
  schedule: {},
  staffCalendars: {},
  availabilityRules: { enabled: true, staffAssignmentMode: 'auto', holdMode: 'pending_confirmed', fallbackDurationMinutes: 60 },
  reminders: { enabled: true, client24h: true, client2h: true },
  googleCalendar: { mode: 'manual-sync', connectedEmail: '', connectedAt: 0, lastSyncedAt: 0, lastSyncCount: 0 },
  features: { birthday: true, waitlist: true, socialProof: true, loadingScreen: true, firstAvailable: true, collectClientName: true, collectClientPhone: true, collectClientEmail: true, collectClientNotes: false, emailUpdates: true, faqEnabled: false, socialLinks: false, location: '', faqs: [] },
  accountProfiles: {},
  themeTemplates: [],
  serviceIndustry: '',
  services: [],
  logoDisplay: { visible: true, alignment: 'left', size: 96, placement: 'title' },
  bannerDisplay: { visible: true, height: 220, position: 'center', placement: 'hero', opacity: 100 },
  logo: '',
  bannerImage: '',
  businessFooterImage: '',
  venuePhotos: [],
  address: '',
  socials: { instagram: '', tiktok: '', facebook: '', website: '' },
  socialPlatforms: { instagram: true, tiktok: true, facebook: true, website: true }
});

export const createGuestDemoWorkspace = () => ({
  settings: createDefaultSettings(),
  bookings: [],
  financeImports: [],
  staffList: [{ id: 'owner', name: 'Admin', color: '#39FF14', role: 'owner', status: 'connected' }],
  clientRecords: [],
  communications: createDefaultCommunications()
});
